server:
  port: 8761

eureka:
  instance:
    hostname: registry
    # 以IP地址注册到服务中心
    prefer-ip-address: true
  server:
    # 关闭自我保护 THE SELF PRESERVATION MODE IS TURNED OFF.THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.
    enable-self-preservation: false
    # 清理无效节点的时间间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 5000
  client:
    # 是否将自己注册到Eureka Server
    registerWithEureka: false
    # 是否从Eureka Server获取注册信息
    fetchRegistry: false
    # 与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，默认是http://localhost:8761/eureka，多个地址可用,分隔
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

security:
  user:
    # 设置用户名密码
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
